/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  type Handlers = {
    'ScrapeArticle': EventHandler<{ requestId: string; url: string; timestamp: unknown }, { topic: 'generate-content'; data: { requestId: string; url: string; title: string; content: string; timestamp: unknown } }>
    'ScheduleContent': EventHandler<{ requestId: string; url: string; title: string; content: { twitter?: unknown; linkedin?: unknown }; metadata?: unknown }, never>
    'GenerateContent': EventHandler<{ requestId: string; url: string; title: string; content: string; timestamp: unknown }, { topic: 'schedule-content'; data: { requestId: string; url: string; title: string; content: { twitter?: unknown; linkedin?: unknown }; metadata?: unknown } }>
    'ContentGenerationAPI': ApiRouteHandler<{ url: string }, ApiResponse<200, { message: string; requestId: string; url: string; status: string }> | ApiResponse<400, { error: string }>, { topic: 'scrape-article'; data: { requestId: string; url: string; timestamp: unknown } }>
  }
}